### ISSUE TITLE
Missing `BeautifulSoup` dependency after ST3.0 upgrade

### ISSUE THREAD

**Issue by pospi** [naokazuterada/MarkdownTOC#103]
Since updating to the final build of ST3 (build 3143), I am getting this error when trying to load the package:

```
reloading plugin MarkdownTOC.MarkdownTOC
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MarkdownTOC in /home/pospi/.config/sublime-text-3/Installed Packages/MarkdownTOC.sublime-package", line 8, in <module>
ImportError: cannot import name BeautifulSoup
```

**Comment by naokazuterada** [comment]
Can you try to restart Sublime ?

**Comment by pospi** [comment]
Weird. I've done full reboots since the upgrade, I swear. It has started working now though!
