### ISSUE TITLE
KeyError: 'depth'

### ISSUE THREAD

**Issue by sebastienbarre** [naokazuterada/MarkdownTOC#125]
This very useful plugin seems to be failing with the latest Sublime. I uninstalled and reinstalled to be sure:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "markdowntoc.markdowntoc_update in /Volumes/Users/barre/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownTOC.sublime-package", line 6, in run
  File "markdowntoc.markdowntoc_insert in /Volumes/Users/barre/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownTOC.sublime-package", line 85, in find_tag_and_insert
  File "markdowntoc.markdowntoc_insert in /Volumes/Users/barre/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownTOC.sublime-package", line 66, in get_toc_open_tag
  File "markdowntoc.markdowntoc_insert in /Volumes/Users/barre/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownTOC.sublime-package", line 383, in get_attributes_from
KeyError: 'depth'
Found styles linked in HTML
```

**Comment by sebastienbarre** [comment]
Sorry, I just realized the major changes in v3.0.0
