### ISSUE TITLE
Support '===' or '---' headings

### ISSUE THREAD

**Issue by naokazuterada** [naokazuterada/MarkdownTOC#9]
Currently support only "#" headings.

**Comment by Parnswir** [comment]
It seems, that this issue is present once again:

```markdown

hello
=====

world
-----

```

This file produces the following error if you try to insert a TOC before the first heading

```
Traceback (most recent call last):
  File "...\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "MarkdownTOC in ...\Sublime Text 3\Installed Packages\MarkdownTOC.sublime-package", line 39, in run
  File "MarkdownTOC in ...\Sublime Text 3\Installed Packages\MarkdownTOC.sublime-package", line 211, in get_toc
  File "MarkdownTOC in ...\Sublime Text 3\Installed Packages\MarkdownTOC.sublime-package", line 220, in update_anchors
TypeError: unsupported operand type(s) for -: 'str' and 'int'
'cannot find TOC tags'
```

Doing the same after both headings works.

**Comment by naokazuterada** [comment]
I fixed this problem.
Excuse me...
